name: CI
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build everything
        run: |
          $CC -o nobuild nobuild.c
          ./nobuild run
        env:
          CC: gcc
          CXX: g++
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build everything
        run: |
          $CC -o nobuild nobuild.c
          ./nobuild run
        env:
          CC: clang
          CXX: clang++
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build everything
        run: |
          $CC -o nobuild nobuild.c
          ./nobuild run
        env:
          CC: clang
          CXX: clang++
# TODO(#4): there is no CI for windows
# TODO(#21): there is no CI build for FreeBSD
